---

- hosts: all
  gather_facts: false
  vars:
    array:
      - Your are running
      - 'json-stdout-ansibleplaybook'
      - third example
    map:
      intro: Your are running
      what: json-stdout-ansibleplaybook
      outro: third example

  tasks:
    - name: json-stdout-ansibleplaybook
      debug:
        msg: |
          Your are running
          'json-stdout-ansibleplaybook'
          third example

    - name: json-stdout-ansibleplaybook from array
      debug:
        msg: "{{ array }}"

    - name: json-stdout-ansibleplaybook from map
      debug:
        msg: "{{ map }}"
