---

- name: Test playbook for user input
  hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: input_this
      prompt: Type in anything
    - name: input_that
      prompt: Type in another thing
  tasks:

    - name: echo user input this
      debug:
        msg: "You typed this: '{{ input_this }}'"
 
    - name: echo user input that
      debug:
        msg: "You typed that: '{{ input_that }}'"
        
